"""
Django settings for advanced_features_and_security project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h0cg7%*ab1yk0_gy4zapye8w1*no$#-1v^d^$73-%=&(hd8o@+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject.bookshelf',
    'LibraryProject.accounts',
]

#  FIXED: Custom user model path
AUTH_USER_MODEL = 'accounts.CustomUser'

AUTH_USER_MODEL = 'bookshelf.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'advanced_features_and_security.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'advanced_features_and_security.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY SETTINGS

# Never run with DEBUG=True in production!
DEBUG = False

# Use secure cookies
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Protect against XSS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Force HTTPS (if deployed with SSL)
SECURE_SSL_REDIRECT = True

# Content Security Policy (optional if using django-csp)
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_STYLE_SRC = ("'self'", 'https://fonts.googleapis.com')
# CSP_SCRIPT_SRC = ("'self'",)

MIDDLEWARE += ['csp.middleware.CSPMiddleware']

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", 'https://fonts.googleapis.com')
CSP_SCRIPT_SRC = ("'self'",)

# SECURITY SETTINGS

DEBUG = False  #  Never run with DEBUG=True in production

SESSION_COOKIE_SECURE = True  #  Sends session cookies only over HTTPS
CSRF_COOKIE_SECURE = True     #  Sends CSRF cookies only over HTTPS

SECURE_BROWSER_XSS_FILTER = True         #  Enables the browser's XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True       #  Prevents browser MIME-type sniffing
X_FRAME_OPTIONS = 'DENY'                 #  Protects against clickjacking by denying framing
SECURE_SSL_REDIRECT = True               #  Redirects all HTTP requests to HTTPS

# Optional: CSP settings if using django-csp middleware
# CSP_DEFAULT_SRC = ("'self'",)               #  Allows content only from this domain
# CSP_STYLE_SRC = ("'self'", 'https://fonts.googleapis.com')  #  Allows safe external styles
# CSP_SCRIPT_SRC = ("'self'",)                #  Restricts JS sources

