# Generated by Django 5.2.4 on 2025-07-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_edit_book', 'Can edit book'), ('can_view_book', 'Can view book')]},
        ),
    ]
